<?php
return array(
'components'=>array(
		'db'=>array(
			'class'=>'CDbConnection',
			'tablePrefix'=>'tbl_',
			'connectionString'=>'mysql:host=localhost;dbname=ammanhs',
			'emulatePrepare'=>true,
			'username'=>'root',
			'password'=>'',
			'charset'=>'utf8',
			//'schemaCachingDuration'=>3600,
			'enableProfiling'=>true,
		),
		'log'=>array(
			'class'=>'CLogRouter',
			'routes'=>array(
				array(
					'class'=>'CProfileLogRoute',
				),
				// uncomment the following to show log messages on web pages
				array(
					'class'=>'CWebLogRoute',
				),
			),
		),
),
'params'=>array(
		'static_host'=>'local.ammanhs.com',
	),
);